auth.py
"""
This will contain all the functions and views related to user authentication
"""

from functools import wraps

from flask import (Blueprint, flash, g, redirect, render_template, request,
                   session, url_for, abort)
from flask_bcrypt import check_password_hash, generate_password_hash

import db

blueprint = Blueprint('auth', __name__, url_prefix='/auth')


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        username = session.get("username", None)
        if not username:
            return redirect(url_for('auth.login', next=request.url))
        g.user = db.get_user(username)
        if g.user is None:
            return redirect(url_for('auth.login', next=request.url))

        db_conn = db.get_database_connection()

        with db_conn.cursor() as cursor:
            sql = ("SELECT"
                        " belongs_to.slug, project.project_id, organisation.name"
                    " FROM"
                        " `user`"
                    " LEFT OUTER JOIN"
                        " belongs_to ON user.username = belongs_to.username"
                    " LEFT OUTER JOIN"
                        " project ON project.slug = belongs_to.slug"
                    " LEFT OUTER JOIN"
                        " organisation ON organisation.slug = belongs_to.slug"
                    " WHERE"
                        " user.username = %s;")
            cursor.execute(sql, (username, ))
            result = cursor.fetchall()
            g.user["orgs"] = {}
            g.orgs = {}

            if result is not None:
                for record in result:
                    organisation_slug = record["slug"]
                    project_id = record["project_id"]
                    org_data = g.orgs.get(organisation_slug, None) or {"name": record["name"]}
                    l = org_data.get("projects", None) or []
                    org_data["projects"] = l + [project_id]
                    g.orgs[organisation_slug] = org_data

        return f(*args, **kwargs)
    return decorated_function



def check_valid_org_and_project(f):
    """
    Used to restrict access to URLs based on the user.
    Returns 404 if it not a valid page.
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if g.user is None:
            # This shouldn't happen, all the endpoints using this decorator must use login_required
            # But just in case.
            return redirect(url_for('auth.login', next=request.url))
        organisation = request.view_args.get('organisation', None) or request.view_args.get('slug', None)
        project_id = request.view_args.get('project_id', None)

        if organisation in g.orgs:
            if project_id is not None and project_id not in g.orgs[organisation]["projects"]:
                # Valid org but invalid project
                abort(404)
        else:
            # Not a valid project
            abort(404)
    
        return f(*args, **kwargs)
    return decorated_function

@blueprint.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template('login.html')
    elif request.method == "POST":
        username = request.form.get("username", None)
        password = request.form.get("password", None)
        user = check_user_login(username, password)
        if not user:
            flash("Invalid username or password", "danger")
            return render_template('login.html', next=request.args.get("next", None))
        else:
            session["username"] = user["username"]
            if request.args.get('next', None):
                return redirect(request.args["next"])
            return redirect(url_for('organisation.organisation'))

@blueprint.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('auth.login'))

@blueprint.route('/me', methods=["GET"])
@login_required
def my_details():
    return g.user or {}


def get_email(email):
    db_conn = db.get_database_connection()
    with db_conn.cursor() as cursor:
        sql = 'SELECT `email` FROM `user` WHERE `email`=%s'
        cursor.execute(sql, (email, ))
        result = cursor.fetchone()
        return result

def check_user_login(username: str, password: str):
    if username and password:
        result = db.get_user(username, with_password=True)
        if result:  
            return result if check_password_hash(result["password"], password) else None 
    return None



@blueprint.route('/signup',methods=["GET","POST"])
def signup():
    if 'username' in session:
        return redirect(url_for('auth.my_details'))
    if request.method == "GET":
        return render_template('signup.html')
    elif request.method == "POST":
        username = request.form.get("username", None)
        first_name = request.form.get("first_name", None)
        last_name = request.form.get("last_name", None)
        email = request.form.get("email", None)
        password = request.form.get("password", None)
        print(f'{username}')

        if username and first_name and last_name and email and password:
            user = db.get_user(username)
            if user is not None:
                flash("Username already exists","danger")
                return render_template('signup.html')
            else:
                _email = get_email(email)
                if _email is not None:
                    flash("Email already exists","danger")
                    return render_template('signup.html')
                else:
                    password_hash = generate_password_hash(password)
                    db_conn = db.get_database_connection()                
                    with db_conn.cursor() as cursor:
                        cursor.execute("INSERT INTO `user`(`username`,`email`,`first_name`,`last_name`,`password`) Values (%s, %s, %s, %s, %s)", (username, email, first_name, last_name, password_hash))
                        db_conn.commit();
                    session["username"] = username
                    return redirect(url_for('organisation.organisation'))
        else:
            if not username:
                flash("Enter Username", "danger")
            if not first_name:
                flash("Enter First name", "danger")
            if not last_name:
                flash("Enter Last name", "danger")
            if not email:
                flash("Enter Email", "danger")
            if not password:
                flash("Enter Password", "danger")
            
            return render_template('signup.html')

templates/partials/flashed_messages.html
{% with messages = get_flashed_messages(with_categories=True)%}
{% if messages %}
  {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
{% endwith %}

templates/partials/sidebar.html
{% set side_bar = [
  (url_for('organisation.view_project', project_id=active_project, slug=g.active_organisation), 'ni ni-atom text-primary', 'Project home'),
  (url_for('organisation.project_dashboard', project_id=active_project, organisation=g.active_organisation), 'ni ni-tv-2 text-primary', 'Dashboard'),
  (url_for('organisation.project_events_dashboard', project_id=active_project, organisation=g.active_organisation), 'fa fa-layer-group text-primary', 'Events'),
  (url_for('organisation.project_sessions_dashboard', project_id=active_project, organisation=g.active_organisation), 'fa fa-mouse-pointer text-primary', 'Sessions'),
] -%}
<!-- Sidenav -->
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header align-items-center">
      <a class="navbar-brand" href="javascript:void(0)">
        <!-- <img src="../assets/img/brand/blue.png" class="navbar-brand-img" alt="Trail"> -->
        <h1>Trail</h1>
      </a>
    </div>
    <hr />
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">

        <h5 class="text-uppercase text-muted mb-2 px-2">Organisation</h5>
        <div class="row justify-content-center my-2">
          <div class="col-12 media align-items-center">
            <span class="avatar rounded-circle">
              <img src="{{ url_for('organisation.upload_file',filename='logos/'+ g.active_organisation) }}">
            </span>
            <div class="media-body ml-2">
              <h3 class=" text-primary">{{ g.orgs[g.active_organisation]["name"] }} </h3>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a class="btn btn-icon btn-outline-secondary btn-sm"
              href="{{ url_for('organisation.view_organisation',slug=g.active_organisation) }}">
              <span class="btn-inner--icon"><i class="fa fa-eye"></i></span>
              <span class="btn-inner--text">View</span>
            </a>
          </div>
          <div class="col">
            <button class="btn btn-icon btn-outline-secondary btn-sm m-0" type="button" id="switchOrgButton"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

              <span class="btn-inner--icon">
                <i class="fa fa-exchange-alt"></i>
              </span>

              <span class="btn-inner--text">Switch</span>
            </button>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="switchOrgButton">
              <h6 class="dropdown-header">Select an organisation</h6>
              {% for organisation_slug in g.orgs %}
              <a class="dropdown-item"
                href="{{ url_for('organisation.view_organisation', slug=organisation_slug) }}">{{ g.orgs[organisation_slug]["name"] }}</a>
              {% endfor %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ url_for('organisation.new_organisation') }}">
                <i class="fa fa-plus"></i>
                Create new
              </a>

            </div>
          </div>
        </div>

        <hr>
        {% if show_select_project_dropdown %}
        <h5 class="text-uppercase text-muted mb-2 px-2">Project</h5>

        <div class="dropdown">
          <button class="btn bg-white btn-block dropdown-toggle" type="button" id="projectDropdownButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ active_project }}
          </button>
          <div class="dropdown-menu" aria-labelledby="projectDropdownButton">
            <h6 class="dropdown-header">Switch project</h6>
            {% for project in g.orgs[g.active_organisation]["projects"] %}
            <a class="dropdown-item"
              href="{{ url_for(request.endpoint, project_id=project, organisation=g.active_organisation, slug=g.active_organisation) }}">{{ project }}</a>
            {% endfor %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('organisation.new_project', slug=g.active_organisation) }}">
              <i class="fa fa-plus"></i>
              New project
            </a>

          </div>
        </div>

        <!-- Nav items -->
        <ul class="navbar-nav">
          {% for href, icon, caption in side_bar %}
          <li class="nav-item">
            <a class="nav-link {% if caption == active_page %} active {% endif %}" href="{{ href }}">
              <i class="{{ icon }}"></i>
              <span class="nav-link-text"> {{ caption }}</span>
            </a>
          </li>
          {% endfor %}
        </ul>
        {% endif %}

      </div>
    </div>
  </div>
</nav>

templates/partials/signed_in_top_nav.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar links -->
        <ul class="navbar-nav align-items-center  ml-md-auto ">
          <li class="nav-item d-xl-none">
            <!-- Sidenav toggler -->
            <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
              </div>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
          <li class="nav-item dropdown">
            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="media align-items-center">
                <div class="media-body  ml-2  d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold">@{{ session.get("username", "") }}</span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu  dropdown-menu-right ">
              <div class="dropdown-header noti-title">
                <h6 class="text-overflow m-0">Welcome!</h6>
              </div>
              <a href="{{ url_for('profile') }}" class="dropdown-item">
                <i class="ni ni-single-02"></i>
                <span>My profile</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="{{ url_for('auth.logout') }}" class="dropdown-item">
                <i class="ni ni-user-run"></i>
                <span>Logout</span>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>