auth.py
"""
This will contain all the functions and views related to user authentication
"""

from functools import wraps

from flask import (Blueprint, flash, g, redirect, render_template, request,
                   session, url_for, abort)
from flask_bcrypt import check_password_hash, generate_password_hash

import db

blueprint = Blueprint('auth', __name__, url_prefix='/auth')


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        username = session.get("username", None)
        if not username:
            return redirect(url_for('auth.login', next=request.url))
        g.user = db.get_user(username)
        if g.user is None:
            return redirect(url_for('auth.login', next=request.url))

        db_conn = db.get_database_connection()

        with db_conn.cursor() as cursor:
            sql = ("SELECT"
                        " belongs_to.slug, project.project_id, organisation.name"
                    " FROM"
                        " `user`"
                    " LEFT OUTER JOIN"
                        " belongs_to ON user.username = belongs_to.username"
                    " LEFT OUTER JOIN"
                        " project ON project.slug = belongs_to.slug"
                    " LEFT OUTER JOIN"
                        " organisation ON organisation.slug = belongs_to.slug"
                    " WHERE"
                        " user.username = %s;")
            cursor.execute(sql, (username, ))
            result = cursor.fetchall()
            g.user["orgs"] = {}
            g.orgs = {}

            if result is not None:
                for record in result:
                    organisation_slug = record["slug"]
                    project_id = record["project_id"]
                    org_data = g.orgs.get(organisation_slug, None) or {"name": record["name"]}
                    l = org_data.get("projects", None) or []
                    org_data["projects"] = l + [project_id]
                    g.orgs[organisation_slug] = org_data

        return f(*args, **kwargs)
    return decorated_function



def check_valid_org_and_project(f):
    """
    Used to restrict access to URLs based on the user.
    Returns 404 if it not a valid page.
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if g.user is None:
            # This shouldn't happen, all the endpoints using this decorator must use login_required
            # But just in case.
            return redirect(url_for('auth.login', next=request.url))
        organisation = request.view_args.get('organisation', None) or request.view_args.get('slug', None)
        project_id = request.view_args.get('project_id', None)

        if organisation in g.orgs:
            if project_id is not None and project_id not in g.orgs[organisation]["projects"]:
                # Valid org but invalid project
                abort(404)
        else:
            # Not a valid project
            abort(404)
    
        return f(*args, **kwargs)
    return decorated_function

@blueprint.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template('login.html')
    elif request.method == "POST":
        username = request.form.get("username", None)
        password = request.form.get("password", None)
        user = check_user_login(username, password)
        if not user:
            flash("Invalid username or password", "danger")
            return render_template('login.html', next=request.args.get("next", None))
        else:
            session["username"] = user["username"]
            if request.args.get('next', None):
                return redirect(request.args["next"])
            return redirect(url_for('organisation.organisation'))

@blueprint.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('auth.login'))

@blueprint.route('/me', methods=["GET"])
@login_required
def my_details():
    return g.user or {}


def get_email(email):
    db_conn = db.get_database_connection()
    with db_conn.cursor() as cursor:
        sql = 'SELECT `email` FROM `user` WHERE `email`=%s'
        cursor.execute(sql, (email, ))
        result = cursor.fetchone()
        return result

def check_user_login(username: str, password: str):
    if username and password:
        result = db.get_user(username, with_password=True)
        if result:  
            return result if check_password_hash(result["password"], password) else None 
    return None



@blueprint.route('/signup',methods=["GET","POST"])
def signup():
    if 'username' in session:
        return redirect(url_for('auth.my_details'))
    if request.method == "GET":
        return render_template('signup.html')
    elif request.method == "POST":
        username = request.form.get("username", None)
        first_name = request.form.get("first_name", None)
        last_name = request.form.get("last_name", None)
        email = request.form.get("email", None)
        password = request.form.get("password", None)
        print(f'{username}')

        if username and first_name and last_name and email and password:
            user = db.get_user(username)
            if user is not None:
                flash("Username already exists","danger")
                return render_template('signup.html')
            else:
                _email = get_email(email)
                if _email is not None:
                    flash("Email already exists","danger")
                    return render_template('signup.html')
                else:
                    password_hash = generate_password_hash(password)
                    db_conn = db.get_database_connection()                
                    with db_conn.cursor() as cursor:
                        cursor.execute("INSERT INTO `user`(`username`,`email`,`first_name`,`last_name`,`password`) Values (%s, %s, %s, %s, %s)", (username, email, first_name, last_name, password_hash))
                        db_conn.commit();
                    session["username"] = username
                    return redirect(url_for('organisation.organisation'))
        else:
            if not username:
                flash("Enter Username", "danger")
            if not first_name:
                flash("Enter First name", "danger")
            if not last_name:
                flash("Enter Last name", "danger")
            if not email:
                flash("Enter Email", "danger")
            if not password:
                flash("Enter Password", "danger")
            
            return render_template('signup.html')

templates/login.html
{% extends "layouts/base_layout.html" %}

{% block title %}Login - Trail{% endblock %}
{% block content %}
  
    <div class="main-content">
        <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
          <div class="container">
            <div class="header-body text-center mb-7">
              <div class="row justify-content-center">
                <div class="col-xl-5 col-lg-6 col-md-8 px-5">
                  <h1 class="text-white">Welcome !</h1>
                </div>
              </div>
            </div>
          </div>
          <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
              <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
            </svg>
          </div>
        </div>
        <!-- Page content -->
        <div class="container mt--8 pb-5">
          <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7">
              <div class="card bg-secondary border-0 mb-0">
                <div class="card-body px-lg-5 py-lg-5">
                  <div class="text-center text-muted mb-4">
                    <small>Sign in to continue</small>
                  </div>
                        {% include "partials/flashed_messages.html"%}
                  <form role="form" action="{{ url_for('auth.login', next=request.args.get('next','')) }}" method="POST">
                    <div class="form-group mb-3">
                      <div class="input-group input-group-merge input-group-alternative">
                        <div class="input-group-prepend">
                          <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                        </div>
                        <input class="form-control" placeholder="Username" name="username" type="text">
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group input-group-merge input-group-alternative">
                        <div class="input-group-prepend">
                          <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                        </div>
                        <input class="form-control" placeholder="Password" name="password" type="password">
                      </div>
                    </div>
                    <div class="text-center">
                      <input type="submit" class="btn btn-primary my-4" value="Sign in">
                    </div>
                  </form>
                </div>
              </div>
              <div class="row mt-3">
                <div class="col-12 text-center">
                  <small>New to Trail?<br/> <a href="{{ url_for('auth.signup') }}" class="text">Create an account</a></small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

templates/profile.html
{% extends "layouts/base_layout.html" %}

{% block title %}Profile - Trail{% endblock %}

{% block content %}
<!-- Header -->
<div class="main-content" id="panel">
  <!-- Topnav -->
  {% include "partials/signed_in_top_nav.html" %}
</div>

<div class="header pb-6 d-flex align-items-center" 
	style="min-height: 500px;
        background: url('/static/assets/images/profile.svg') var(--primary) no-repeat;
        background-size: 35%;
        background-position: center right 15%">
  <!-- Mask -->
  <!-- <span class="mask bg-gradient-default opacity-8"></span> -->
  <!-- Header container -->
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-7 col-md-10">
        <h1 class="display-2 text-white">Hello {{ profile.username }}!</h1>
        <p class="text-white mt-0 mb-5">This is your profile page.You can see and edit your profile here.</p>
        <a href="{{ url_for('organisation.organisation') }}" class="btn btn-neutral">Home</a>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid mt--6">
  	<div class="row justify-content-md-center">
		<div class="col-xl-8 order-xl-1">
		  <div class="card">
		    <div class="card-header">
		      <div class="row align-items-center">
		      	<div class="col-8">
		      		<h3 class="mb-0">Profile details</h3>
		      	</div>
		      </div>
		    </div>
		    <div class="card-body">
		    	<form action="{{ url_for('profile') }}" method="POST" role="form">
		    	{% include "partials/flashed_messages.html"%}
		    	<div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username">First name</label>
                        <input type="text" id="first-name" class="form-control" maxlength="30" name="first_name" value="{{ profile.first_name }}">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Last name</label>
                        <input type="text" id="last-name" class="form-control" name="last_name" maxlength="30" value="{{ profile.last_name }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Email address</label>
                        <input type="email" id="email-address" class="form-control" name="email" maxlength="150" value="{{ profile.email }}">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">Password</label>
                        <input type="password" id="input-password" class="form-control" name="password" maxlength="60" placeholder="password">
                      </div>
                    </div>
                    <div class="row">
                    	<div class="col-lg-6">
               				<input type="submit" class="btn btn-primary mt-4" value="Edit Profile">
              			</div>
              		</div>
                  </div>
                </div>
            	</form>
		    </div>
		  </div>
		</div>
	</div>
</div>

{% endblock content %}

templates/signup.html
{% extends "layouts/base_layout.html" %} 

{% block title %}Sign up - Trail{% endblock %}

{% block content %}
  <div class="main-content">
    <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
      <div class="container">
        <div class="header-body text-center mb-10">
          <div class="row justify-content-center">
            <div class="col-xl-7 col-lg-6 col-md-8 px-5">
              <h1 class="text-white">Trail</h1>
              <p class="text-lead text-white">Create your account to continue working</p>
            </div>
          </div>
        </div>
      </div>
      <div class="separator separator-bottom separator-skew zindex-100">
        <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
        </svg>
      </div>
    </div>
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
          <div class="card bg-secondary border-0">
            <div class="card-body px-lg-5 py-lg-5">
                    {% include "partials/flashed_messages.html"%}
              <form role="form" action="{{ url_for('auth.signup') }}" method="POST">
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                    </div>
                    <input class="form-control" placeholder="Username" name="username" maxlength="30" type="text">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                    </div>
                    <input class="form-control" placeholder="First name" name="first_name" maxlength="30" type="text">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                    </div>
                    <input class="form-control" placeholder="Last name" name="last_name" maxlength="30" type="text">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                    </div>
                    <input class="form-control" placeholder="Email" name="email" maxlength="150" type="email">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                    </div>
                    <input class="form-control" placeholder="Password" name="password" maxlength="60" type="password">
                  </div>
                </div>
                <div class="text-center">
                  <input type="submit" class="btn btn-primary mt-4" value="Create account">
                </div>
              </form>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-12 text-center">
              <small>Already have an account?<br/> <a href="{{ url_for('auth.login') }}" class="text">Sign in</a></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}